# Generated by Django 4.0.1 on 2022-01-29 10:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tempName', models.CharField(max_length=25)),
                ('sharePrice', models.IntegerField(default=0)),
                ('totalNoOfShares', models.IntegerField(default=0)),
                ('sharesLeft', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensex', models.FloatField(default=0)),
                ('spread', models.IntegerField(default=0)),
                ('LiveText', models.CharField(max_length=100)),
                ('LeaderboardSize', models.IntegerField(default=100)),
                ('LeaderBoardUpdateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('bidRangePercent', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('registrationKey', models.CharField(default='abcde', max_length=20)),
                ('startStopMarket', models.BooleanField(default=True)),
                ('startNews', models.BooleanField(default=False)),
                ('NewsCounter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=-1)),
                ('numberOfShares', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=200000)),
                ('netWorth', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
